### ISSUE TITLE
There is no Helm Chat for Farm

### ISSUE THREAD

**Issue by juliosmelo** [corda/cenm-deployment#25]
There is a step on the doc https://docs.r3.com/en/platform/corda/1.5/cenm/deployment-kubernetes.html#manual-bootstrap to install **farm** chart. But, this chart is not present in the repo. 

helm install cenm-farm farm --set prefix=cenm --set acceptLicense=Y

**Comment by tomstark99** [comment]
Hi @juliosmelo I can't see the above-mentioned command on that wiki page. Afaik the farm service has been renamed to the gateway service since CENM 1.4
